services:
  bia:
    build:
      context: "."
    image: bia-today
    command: server
    tty: true
    stdin_open: true
    volumes:
      - .:/bia
      - ./bundle_cache:/bundle:rw,delegated
    env_file:
      - .env
    expose:
      - "3000"
    # depends_on:
    #   - redis

  nginx:
    image: nginx:1.19.4
    depends_on:
      - bia
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/var/conf/certbot/:ro
    ports:
      - "8080:80"
      - "443:443"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  # redis:
  #   image: redis:6-alpine
  #   ports:
  #     - "6379:6379"

  # sidekiq:
  #   depends_on:
  #     # - "db"
  #     - "redis"
  #   image: bia-today
  #   command: sidekiq
  #   volumes:
  #     - .:/app
  #     - ./bundle_cache:/bundle:rw,delegated
  #     - ./node_modules:/app/node_modules:rw,delegated
  #   environment:
  #     REDIS_URL: redis://redis:6379/1
